version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/autobox-backend
hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
